// Ontario private/alt lender database for the Lender Scout tool.
// Source: ontario-lender-screening skill knowledge base. Verify current
// terms directly with the lender before relying on this for outreach —
// policies change and several fields below are marked "unconfirmed" for
// a reason.
//
// Update this file (and, if it should stay in sync, the skill's own
// table) whenever a lender's terms change or a file gets accepted/declined.

const LENDER_DATA = [
  {
    name: "Antrim Investments",
    regionTags: ["ontario", "major centres"],
    excludedRegions: ["niagara", "st. catharines", "st catharines"],
    ltvCap: null,
    ltvNotes: "1st & 2nd position, $25K–$3M loan range; no per-region LTV cap published.",
    creditFloor: null,
    creditNotes: "Self-employed / stated-income / low-beacon niche, 45+ years in business — likely tolerant of bruised credit, not explicitly published.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Stated-income program available.",
    conditionTolerance: "unspecified",
    conditionNotes: "",
    channel: "Direct contact preferred",
    contactName: "Navee",
    contactEmail: "navee@antriminvestments.com",
    altEmails: ["applications@antriminvestments.com", "info@antriminvestments.com"],
    phone: "416-898-5692 / TF 1-888-550-6039",
    licence: "",
    declines: [
      { date: "2026-08", file: "Sivatharsan — 95 Blanchard Cres, Angus/Essa Twp", region: "Simcoe County", ltv: "~64%", reason: "not specified" },
    ],
  },
  {
    name: "Magenta Capital Corporation",
    regionTags: [],
    excludedRegions: ["st. catharines", "st catharines"],
    ltvCap: null,
    ltvNotes: "Not published.",
    creditFloor: null,
    creditNotes: "Equity/alt-criteria based.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Not published.",
    conditionTolerance: "unspecified",
    conditionNotes: "",
    channel: "Broker portal (Filogix/Lendesk) or regional sales manager",
    contactName: "",
    contactEmail: "",
    altEmails: [],
    phone: "1-888-267-1744",
    licence: "",
    declines: [],
  },
  {
    name: "MCF Investments",
    regionTags: ["niagara"],
    excludedRegions: [],
    ltvCap: 55,
    ltvNotes: "~55% in lower-liquidity Niagara-area markets to protect equity cushion (vs ~70% general cap elsewhere). Simcoe County coverage not confirmed — treat as Niagara-only.",
    creditFloor: null,
    creditNotes: "Equity-based, not credit-driven.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Not required.",
    conditionTolerance: "unspecified",
    conditionNotes: "Not specified.",
    channel: "Email",
    contactName: "",
    contactEmail: "",
    altEmails: [],
    phone: "",
    licence: "",
    declines: [],
  },
  {
    name: "Home Credits",
    regionTags: ["st. catharines", "st catharines"],
    excludedRegions: [],
    ltvCap: 65,
    ltvNotes: "65–70% cap in the St. Catharines market. Simcoe County coverage not confirmed.",
    creditFloor: null,
    creditNotes: "Not published.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Unknown.",
    conditionTolerance: "unspecified",
    conditionNotes: "Unknown.",
    channel: "Email",
    contactName: "",
    contactEmail: "deals@homecredits.ca",
    altEmails: [],
    phone: "",
    licence: "",
    declines: [],
  },
  {
    name: "Interfinance Mortgage Corporation",
    regionTags: ["gta", "toronto"],
    excludedRegions: [],
    ltvCap: 75,
    ltvNotes: "80% product is GTA-only; will consider 75% elsewhere if property is in good condition.",
    creditFloor: null,
    creditNotes: "Does not do \"bad credit\" at 75% LTV.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Unknown.",
    conditionTolerance: "low",
    conditionNotes: "Requires good condition. Runs a dedicated Mortgage & Tax Arrears service line.",
    channel: "Direct contact preferred",
    contactName: "Kiran",
    contactEmail: "kiran@interfinance.ca",
    altEmails: ["info@interfinance.ca"],
    phone: "416-445-4890",
    licence: "FSRA Lic #12004",
    declines: [
      { date: "2026-08", file: "Sivatharsan — 95 Blanchard Cres, Angus/Essa Twp", region: "Simcoe County", ltv: "~64%", reason: "not specified" },
    ],
  },
  {
    name: "Lendmax Capital",
    regionTags: ["welland", "st. catharines", "st catharines"],
    excludedRegions: [],
    ltvCap: 75,
    ltvNotes: "75% confirmed cap for Welland/St. Catharines. Simcoe County coverage not confirmed.",
    creditFloor: 0,
    creditNotes: "Has accepted sub-600 credit + a discharged consumer proposal with no seasoning objection in past files.",
    cpBkSeasoningMonths: 0,
    incomeDocsRequired: false,
    incomeNotes: "Not required.",
    conditionTolerance: "unspecified",
    conditionNotes: "Not raised as a blocker in past files.",
    channel: "Email",
    contactName: "",
    contactEmail: "deals@lendmax.ca",
    altEmails: [],
    phone: "",
    licence: "",
    declines: [],
  },
  {
    name: "Mercury Mortgages",
    regionTags: ["niagara"],
    excludedRegions: [],
    ltvCap: 75,
    ltvNotes: "Quoted 75% at ~6.99% + 1–1.5% fee, subject to credit.",
    creditFloor: 550,
    creditNotes: "OK with low-600s / mid-500s credit verbally.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Not a primary factor.",
    conditionTolerance: "low",
    conditionNotes: "Has declined specifically over property condition photos.",
    channel: "Email",
    contactName: "",
    contactEmail: "deals@mercurymortgages.com",
    altEmails: [],
    phone: "",
    licence: "",
    declines: [],
  },
  {
    name: "VWR Capital",
    regionTags: ["niagara"],
    excludedRegions: [],
    ltvCap: null,
    ltvNotes: "\"No-TDS/GDS\" program. Broader BC/AB/SK/MB/ON reach claimed on company site — other ON regions beyond Niagara not confirmed.",
    creditFloor: null,
    creditNotes: "Not published.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Not required.",
    conditionTolerance: "low",
    conditionNotes: "Has declined specifically over condition (\"dated\").",
    channel: "Email",
    contactName: "",
    contactEmail: "",
    altEmails: [],
    phone: "",
    licence: "",
    declines: [],
  },
  {
    name: "Alta West Capital",
    regionTags: ["gta", "hamilton", "kitchener", "waterloo", "london", "ottawa", "barrie"],
    excludedRegions: [],
    ltvCap: null,
    ltvNotes: "Not published.",
    creditFloor: null,
    creditNotes: "Not published.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: true,
    incomeNotes: "Requires income verification — not a fit for equity-only/no-income files.",
    conditionTolerance: "unspecified",
    conditionNotes: "",
    channel: "Email/portal",
    contactName: "",
    contactEmail: "info@awcapital.ca",
    altEmails: [],
    phone: "1-888-554-9075",
    licence: "",
    declines: [
      { date: "2026-08", file: "Sivatharsan — 95 Blanchard Cres, Angus/Essa Twp", region: "Simcoe County", ltv: "~64%", reason: "not specified (Angus not separately named in published service area)" },
    ],
  },
  {
    name: "CMI (Canadian Mortgages Inc)",
    regionTags: ["st. catharines", "st catharines"],
    excludedRegions: [],
    ltvCap: 85,
    ltvNotes: "Three fund tiers: Prime avg <65% LTV, Balanced avg <75% LTV, High Yield avg <85% LTV. Large Ontario-wide footprint makes Barrie/Simcoe County plausible but not explicitly confirmed per-city — verify via broker portal.",
    creditFloor: null,
    creditNotes: "Alt-lender, equity-focused.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Flexible.",
    conditionTolerance: "unspecified",
    conditionNotes: "Unknown — proactively offer condition detail.",
    channel: "Direct contact / broker portal (Filogix / Velocity / Lendesk)",
    contactName: "Mary Lepone",
    contactEmail: "mary.lepone@thecmigroup.ca",
    altEmails: ["info@thecmigroup.ca"],
    phone: "1-888-465-4350",
    licence: "",
    declines: [],
  },
  {
    name: "Lendworth MIC",
    regionTags: [
      "niagara", "st. catharines", "st catharines", "niagara falls", "welland", "thorold", "pelham",
      "simcoe county", "barrie", "innisfil", "oro-medonte", "midhurst", "essa township", "essa twp", "alcona", "angus",
    ],
    excludedRegions: [],
    ltvCap: 85,
    ltvNotes: "No fixed cap published on site — verify per file (general private market range 75–85% typical).",
    creditFloor: 0,
    creditNotes: "Equity-based; site states bad/bruised credit is not a deal-breaker.",
    cpBkSeasoningMonths: 0,
    incomeDocsRequired: false,
    incomeNotes: "States no income docs required; also markets to self-employed borrowers.",
    conditionTolerance: "medium",
    conditionNotes: "Site states it lends on rural/semi-rural and non-conforming residential property types; not confirmed for severe condition issues. Runs a dedicated Stop Power of Sale / Mortgage in Arrears line.",
    channel: "Direct contact / online application",
    contactName: "Steve",
    contactEmail: "steve@lendworth.ca",
    altEmails: ["info@lendworth.ca"],
    phone: "905-597-1225",
    licence: "",
    declines: [],
  },
  {
    name: "DV Capital Corporation",
    regionTags: [
      "barrie", "innisfil", "bradford", "new tecumseth", "alliston", "collingwood",
      "midland", "penetanguishene", "orillia", "simcoe county",
    ],
    excludedRegions: [],
    ltvCap: null,
    ltvNotes: "Not explicitly published — request directly.",
    creditFloor: null,
    creditNotes: "Not published — markets broadly to \"mortgage arrears\" and credit-challenged files.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Not published — verify.",
    conditionTolerance: "medium",
    conditionNotes: "Lends on detached, semi-detached, condo, cottage, rural, and other property types per site, suggesting reasonable flexibility. Extensive dedicated Stop Power of Sale content.",
    channel: "Email / phone, 7 days/week per site",
    contactName: "",
    contactEmail: "info@dvcapitalcorp.com",
    altEmails: [],
    phone: "416-839-5874 / TF 1-866-839-5874",
    licence: "FSRA Lic #13186",
    declines: [],
  },
  {
    name: "Ontario Mortgage Capital (OMC)",
    regionTags: ["oakville"],
    excludedRegions: [],
    ltvCap: 75,
    ltvNotes: "Up to 75% of home value. Markets as \"Ontario Mortgage Capital\" broadly but does not publish a specific town list — coverage outside Oakville area not explicitly confirmed.",
    creditFloor: 0,
    creditNotes: "Markets explicitly to \"credit challenges, bankruptcy, consumer proposal\" — no stated floor. \"NO CREDIT OR INCOME REQUIREMENTS\" per site.",
    cpBkSeasoningMonths: 0,
    incomeDocsRequired: false,
    incomeNotes: "\"NO CREDIT OR INCOME REQUIREMENTS\" per site.",
    conditionTolerance: "unspecified",
    conditionNotes: "Not specified.",
    channel: "Email / broker-agent submission form",
    contactName: "",
    contactEmail: "info@ontariomortgagecapital.com",
    altEmails: [],
    phone: "289-952-2104",
    licence: "FSRA Lic #12385",
    declines: [],
  },
  {
    name: "Richview Capital MIC",
    regionTags: ["gta", "vaughan", "woodbridge", "hamilton", "ottawa", "waterloo region", "waterloo"],
    excludedRegions: [],
    ltvCap: 75,
    ltvNotes: "Up to 75% LTV on residential firsts (case by case); combined LTV up to 75% on seconds. Site explicitly warns rural/specialty properties may face higher rates or lower LTV.",
    creditFloor: 0,
    creditNotes: "Bruised/limited credit evaluated case-by-case, not disqualifying.",
    cpBkSeasoningMonths: null,
    incomeDocsRequired: false,
    incomeNotes: "Not required — asset-based underwriting.",
    conditionTolerance: "unspecified",
    conditionNotes: "Not specified for rural properties — site flags rural/specialty as a risk factor for rate/LTV.",
    channel: "Email",
    contactName: "",
    contactEmail: "info@richviewcapitalmic.com",
    altEmails: [],
    phone: "416-307-2336",
    licence: "Mortgage Administrator Licence #13171, ONMICA member",
    declines: [],
  },
];
